---
title: "Germany RNASeq Libraries"
author: "Isabel Kline"
output:  
  html_document:
    keep_md: true
    theme: cosmo
    toc:  True
    toc_float:  True
    toc_depth: 2
    number_sections:  true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

[Drive folder link](https://drive.google.com/drive/u/0/folders/1Hol6ktlDViiKfrVa1tLDwSl3-bCFDLBG)

Extracted total RNA was normalized and the mRNA fraction was enriched via the NEBNext Poly(A) mRNA Magnetic Isolation Module. The samples were prepared for sequencing using the NEBNext® Ultra II Directional RNA Library Prep Kit for Illumina® and indexed using the NEBNext® Multiplex Oligos for Illumina. The protocol followed for library preparation modified fragment time to 10 minutes at 94 C, extended the first strand cDNA synthesis incubation 42 C incubation time to 50 minutes and limited the PCR cycles to 10. 

Upon completion of library prep of all 96 samples proceed to pool samples for sequencing.

[Pooling Lab Notebook Entry](https://isabel-kline.github.io/Kelley_Lab_Notebook/Germany_RNASeq_Pooling.html#1_Summary)

# Summary

Gills first, sample count: 83.

remixed order from extraction order

Brains second, sample count: 18.

remixed order from extraction order

Library prep bar: need 1 ug input

PCR cycles: 10

Month of Experiment: 7/24

redid library prep on 8 samples with poor library prep yield using the same indexes as from the first round.

# Data

<details>

<summary>Click me for table of sample concentrations and indices </summary>

First pass library prep results:

| Library | Qubit (ng/ul) | i7 index iD |
|:-------:|:-------------:|:-----------:|
|    1    |     6.05      |    P1-A1    |
|    2    |     5.86      |   P13-B1    |
|    3    |      3.7      |   P25-C1    |
|    4    |     3.23      |   P37-D1    |
|    5    |     2.49      |   P49-E1    |
|    6    |     2.29      |   P61-F1    |
|    7    |     2.85      |   P73-G1    |
|    8    |     6.57      |   P85-H1    |
|    9    |     3.92      |    P2-A2    |
|   10    |     11.8      |   P14-B2    |
|   11    |     11.1      |   P26-C2    |
|   12    |     1.29      |   P38-D2    |
|   13    |     10.6      |   P50-E2    |
|   14    |     9.66      |   P62-F2    |
|   15    |     8.81      |   P74-G2    |
|   16    |      5.7      |   P86-H2    |
|   17    |     0.183     |    P3-A3    |
|   18    |     0.253     |   P15-B3    |
|   19    |     0.178     |   P27-C3    |
|   20    |     0.36      |   P39-D3    |
|   21    |     0.246     |   P51-E3    |
|   22    |     4.35      |   P63-F3    |
|   23    |     0.718     |   P75-G3    |
|   24    |     2.98      |   P87-H3    |
|   25    |     11.6      |    P4-A4    |
|   26    |     9.71      |   P16-B4    |
|   27    |      6.8      |   P28-C4    |
|   28    |     8.61      |   P40-D4    |
|   29    |     10.8      |   P52-E4    |
|   30    |      8.5      |   P64-F4    |
|   31    |     5.18      |   P76-G4    |
|   32    |     7.01      |   P88-H4    |
|   33    |     4.25      |    P5-A5    |
|   34    |     3.23      |   P17-B5    |
|   35    |     3.44      |   P29-C5    |
|   36    |     4.51      |   P41-D5    |
|   37    |     2.39      |   P53-E5    |
|   38    |     1.11      |   P65-F5    |
|   39    |     2.91      |   P77-G5    |
|   40    |     3.75      |   P89-H5    |
|   41    |      14       |    P6-A6    |
|   42    |     12.2      |   P18-B6    |
|   43    |     14.6      |   P30-C6    |
|   44    |     14.1      |   P42-D6    |
|   45    |     10.7      |   P54-E6    |
|   46    |     13.4      |   P66-F6    |
|   47    |     18.7      |   P78-G6    |
|   48    |      18       |   P90-H6    |
|   49    |      13       |    P7-A7    |
|   50    |     12.8      |   P19-B7    |
|   51    |     13.8      |   P31-C7    |
|   52    |     11.6      |   P43-D7    |
|   53    |     12.1      |   P55-E7    |
|   54    |     11.2      |   P67-F7    |
|   55    |     14.4      |   P79-G7    |
|   56    |      26       |   P91-H7    |
|   57    |     21.7      |    P8-A8    |
|   58    |     14.2      |   P20-B8    |
|   59    |     17.3      |   P32-C8    |
|   60    |     15.4      |   P44-D8    |
|   61    |      14       |   P56-E8    |
|   62    |     23.5      |   P68-F8    |
|   63    |     36.1      |   P80-G8    |
|   64    |     11.7      |   P92-H8    |
|   65    |     15.1      |    P9-A9    |
|   66    |      24       |   P21-B9    |
|   67    |     27.9      |   P33-C9    |
|   68    |     7.62      |   P45-D9    |
|   69    |     15.3      |   P57-E9    |
|   70    |     16.2      |   P69-F9    |
|   71    |     24.1      |   P81-G9    |
|   72    |     28.1      |   P93-H9    |
|   73    |      16       |   P10-A10   |
|   74    |     18.2      |   P22-B10   |
|   75    |     15.3      |   P34-C10   |
|   76    |     18.1      |   P46-D10   |
|   77    |      12       |   P58-E10   |
|   78    |     17.1      |   P70-F10   |
|   79    |     20.9      |   P82-G10   |
|   80    |     21.6      |   P94-H10   |
|   81    |     33.2      |   P11-A11   |
|   82    |     39.3      |   P23-B11   |
|   83    |     20.2      |   P35-C11   |
|   84    |     30.5      |   P47-D11   |
|   85    |     40.7      |   P59-E11   |
|   86    |      44       |   P71-F11   |
|   87    |     39.6      |   P83-G11   |
|   88    |     28.6      |   P95-H11   |
|   89    |     31.9      |   P12-A12   |
|   90    |     31.5      |   P24-B12   |
|   91    |     37.4      |   P36-C12   |
|   92    |     28.8      |   P48-D12   |
|   93    |     30.2      |   P60-E12   |
|   94    |     34.7      |   P72-F12   |
|   95    |     36.4      |   P84-G12   |
|   96    |     34.3      |   P96-H12   |

Redo's library prep results

| Library | Qubit (ng/ul) | i7 index iD |
|:-------:|:-------------:|:-----------:|
|   12b   |      3.7      |   P38-D2    |
|   17b   |     36.8      |    P3-A3    |
|   18b   |     26.6      |   P15-B3    |
|   19b   |     20.4      |   P27-C3    |
|   20b   |     30.2      |   P39-D3    |
|   21b   |      27       |   P51-E3    |
|   23b   |     36.5      |   P75-G3    |
|   38b   |     10.9      |   P65-F5    |

</details>

# Sample Storage

**Gills -**

tube ids: HG24001 - HG24083

box label:

storage location and temperature: Kelley Lab -20

**Brains -**

tube ids: HB24001 - HB24083

box label:

storage location and temperature: Kelley Lab -20

**RNA extracts:**

tube ids: E##\_HG01-E##HG83

boxes: Germany RNA Seq Extractions Summer '24 MIOK Box \# of 2

storage location and temperature: CBB Freezer Room -80

**RNA libraries:**

tube ids: Germany RNA Seq 1-96

box: Germany RNA Seq Libraries Summer '24 MIOK

storage location and temperature: Kelley Lab -20

# [Exp23_Protocol](https://docs.google.com/spreadsheets/d/1KRz4BxfZMiVuNSRogQ07To1Xo2KI_hLexjCjcoXvzPQ/edit#gid=1649175478)

-   target insert size of 300 nt

-   PCR cycles: 10

kit's used:

**NEBNext Poly(A) mRNA Magnetic Isolation Module**

Part no: E7490

O: 7/09/24

**NEBNext® Ultra II Directional RNA Library Prep Kit for Illumina®**

Part no: E7760L

O: 7/09/24

**NEBNext® Multiplex Oligos for Illumina® (96 Index Primers)**

Part no: E6609S

lot: 10188264

O: 7/09/24 by MIOK

# Log

<details>

<summary>Click me for log entries </summary>

### 07/09/24

32 libraries. 7 samples yield was 20 ng or less. Consider these libraries to be failures.

It seems like the 3rd strip of samples had something occurr during processing that inhibited them.

possible causes:

-   didn't add a reagent to a strip of samples?

-   kit efficacy fell off?

next steps: process 8 samples only in next batch and see what happens

### 07/11/24

Batch 2 - 8 samples. concentration of libraries ranged from 1.11ng/ul to 4.51 ng/ul

yield is pretty low.

Overall thoughts:

-   stick with 300 bp insert. Could up pcr cycles to 12 in future projects

-   change to 200 bp insert, pcr 10 and see if yield is signif diff

-   could i lower input of extract?

-   more aggressively mix ligation

### 07/16/24

Batch 3 - 16 samples. concentration of libraries 10 - 26 ng/ul

yield is better!

things I thought I did well here:

-   put enhancer master mix into fresh tubes prior to end of end prep. add in adaptors to sample tubes then transfer sample/diluted adapter into enhancer master mix

-   more steadily mix ligation

### 07/26/24

all done with library prep sample processing.

redid library prep on 8 samples with extremely poor yield. used the same indexes on the samples as was used in the first attempt. Did this by using the overage amount left in the index plate. Amount of index used was \<5 ul apiece about 3.5 ul.

Yield was sufficient for two samples and great for 6 samples

</details>
