---
title: "Gillii Gill RNA Libraries"
author: "Isabel Kline"
output:  
  html_document:
    keep_md: true
    theme: cosmo
    toc:  True
    toc_float:  True
    toc_depth: 2
    number_sections:  true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

[Drive folder link](https://drive.google.com/drive/u/0/folders/1N9ebukVfd9IsLPw2OFkqJCr_8oMp0GTy)

Extracted total RNA was normalized and the mRNA fraction was enriched via the NEBNext Poly(A) mRNA Magnetic Isolation Module. The samples were prepared for sequencing using the NEBNext® Ultra II Directional RNA Library Prep Kit for Illumina® and indexed using the NEBNext® Multiplex Oligos for Illumina. The protocol followed for library preparation modified fragment time to 10 minutes at 94 C, extended the first strand cDNA synthesis incubation 42 C incubation time to 50 minutes and limited the PCR cycles to 10. 

Upon completion of library prep pooled all 24 samples together.

[Link to Pooling](https://isabel-kline.github.io/Kelley_Lab_Notebook/Gillii_RNA_Pooling.html#1_Summary)

# Summary

Gills, sample count: 24.

remixed order from extraction order

normalization prior to Library prep : 1 ug input

PCR cycles: 10

Month of Experiment: 8/24

# Data

<details>

<summary>Click me for table of sample concentrations and indices</summary>

|  Library  | Tube ID | Qubit (ng/ul) | i7 index iD |
|:---------:|---------|:-------------:|:-----------:|
| BWR24_001 | 1       |     13.2      |   P10-A10   |
| BWR24_002 | 2       |     16.3      |   P22-B10   |
| BWR24_029 | 3       |     14.2      |   P34-C10   |
| BWR24_034 | 4       |     16.0      |   P46-D10   |
| BWR24_004 | 5       |     17.8      |   P58-E10   |
| BWR24_025 | 6       |     15.7      |   P70-F10   |
| BWR24_028 | 7       |      9.6      |   P82-G10   |
| BWR24_008 | 8       |     15.2      |   P94-H10   |
| BWR24_036 | 9       |     11.7      |   P11-A11   |
| BWR24_005 | 10      |     19.1      |   P23-B11   |
| BWR24_007 | 11      |     16.8      |   P35-C11   |
| BWR24_012 | 12      |     15.0      |   P47-D11   |
| BWR24_032 | 13      |     19.1      |   P59-E11   |
| BWR24_033 | 14      |     18.0      |   P71-F11   |
| BWR24_031 | 15      |     14.6      |   P83-G11   |
| BWR24_027 | 16      |     21.3      |   P95-H11   |
| BWR24_003 | 17      |     11.9      |   P12-A12   |
| BWR24_010 | 18      |     16.1      |   P24-B12   |
| BWR24_035 | 19      |     15.2      |   P36-C12   |
| BWR24_026 | 20      |     13.5      |   P48-D12   |
| BWR24_030 | 21      |     17.3      |   P60-E12   |
| BWR24_011 | 22      |     16.8      |   P72-F12   |
| BWR24_009 | 23      |     15.1      |   P84-G12   |
| BWR24_006 | 24      |     21.1      |   P96-H12   |

</details>

# Sample Storage

**Gills** *-*

tube ids: BWR24_0##

box label:BWR24_001 to. Costa Rica RNALater filled 12/06/23

storage location and temperature: Kelley Lab -80

**RNA extracts -**

tube ids: 0##\_E##

boxes: Gillii Gill RNA Seq Extractions Summer '24 MIOK Box 1 of 1

storage location and temperature: CBB Freezer Room -80

**RNA libraries:**

tube ids: 1-24

box: Gillii Gill RNA Seq Libraries Summer '24 MIOK

storage location and temperature: Kelley Lab -20

# [Exp29_Protocol](https://docs.google.com/spreadsheets/d/1336Sl0eiGhrzxf5FDq5jDrtsFDEfrcXo-OResmpFPak/edit?gid=1778786204#gid=1778786204)

-   target insert size of 300 nt

-   PCR cycles: 10

kit's used:

**NEBNext Poly(A) mRNA Magnetic Isolation Module**

Part no: E7490

O: 7/09/24

**NEBNext® Ultra II Directional RNA Library Prep Kit for Illumina®**

Part no: E7760L

O: 7/09/24

**NEBNext® Multiplex Oligos for Illumina® (96 Index Primers)**

Part no: E6609S

lot: 10188264

O: 7/09/24 by MIOK

# Log

<details>

<summary>Click me for log entries</summary>

### 08/09/24

Completed library prep of all 24 samples in one go. Library concentrations all looked okay.

</details>
