---
title: "Gillii Gills RNASeq"
author: "Isabel Kline"
output:  
  html_document:
    keep_md: true
    theme: cosmo
    toc:  FALSE
    toc_float:  FALSE
    number_sections:  true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

[Drive folder link](https://drive.google.com/drive/folders/1N9ebukVfd9IsLPw2OFkqJCr_8oMp0GTy)

All samples were stored in RNALater solution. The gill arch samples were homogenized in MP Bio Matrix A tubes using a Fast Prep 5G with cool prep adapter. Gill arch RNA was then extracted using the NEB monarch total RNA MiniPrep kit following the standard tissue protocol for the kit with one modification, a proteinase K incubation time of 15 minutes at 300 rpm.

Extracted total RNA was normalized and the mRNA fraction was enriched via the NEBNext Poly(A) mRNA Magnetic Isolation Module. The samples were prepared for sequencing using the NEBNext® Ultra II Directional RNA Library Prep Kit for Illumina® and indexed using the NEBNext® Multiplex Oligos for Illumina. The protocol followed for library preparation modified fragment time to 10 minutes at 94 C, extended the first strand cDNA synthesis incubation 42 C incubation time to 50 minutes and limited the PCR cycles to 10. 

## [Extractions](https://isabel-kline.github.io/Kelley_Lab_Notebook/Gillii_RNA_Extractions.html)

## [Library Prep](https://isabel-kline.github.io/Kelley_Lab_Notebook/Gilli_RNA_Libraries.html#1_Summary)

## [Pooling](https://isabel-kline.github.io/Kelley_Lab_Notebook/Gillii_RNA_Pooling.html#1_Summary)
