---
title: "Germany RNASeq Extractions"
author: "Isabel Kline"
output:  
  html_document:
    keep_md: true
    theme: cosmo
    toc:  true
    toc_float:  true
    number_sections:  true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary

### Overview

details:

[Drive folder link](https://drive.google.com/drive/u/0/folders/1Hol6ktlDViiKfrVa1tLDwSl3-bCFDLBG)

### Planning

Extraction plan:

##### Sequencing strategy

# Sample data

Experiment XX

Month of Experiment: 6/24

## Sample Storage

##### Gills -

tube id:

box label:

storage location and temperature:

##### RNA extracts:

tube ids:

box:

storage location and temperature:

# [ExpXX_Protocol](https://docs.google.com/spreadsheets/d/1KRz4BxfZMiVuNSRogQ07To1Xo2KI_hLexjCjcoXvzPQ/edit#gid=1649175478)

## Materials List

|     |     |     |     |
|-----|-----|-----|-----|
|     |     |     |     |
|     |     |     |     |
|     |     |     |     |
|     |     |     |     |
|     |     |     |     |
|     |     |     |     |

## Kit Particulars & Lot Numbers

| part                                                | part no | lot |
|-----------------------------------------------------|---------|-----|
| Lysing Matrix A tube                                |         |     |
| NEB monarch total RNA MiniPrep kit - 1st kit opened | T2010S  |     |
|                                                     |         |     |

kit details

**1st kit**

O: 3/24 by Blair Perry, consumed a couple rxns (unkown specific amount)

-   proteinase K reconstituted 6/10/24 by MIOK, made 4 aliquots total, stored in the -20

-   DNAse 1 reconstituted 3/24 by Blair Perry\* not aliquoted, stored in the -20

-   RNA Wash Buffer mixed with 200 proof EtOH 3/24 by Blair Perry, stored at RT

|     |
|-----|
|     |

# Log

### 06/11/24

did 12 extraction reactions with Owen and Dalya shadowing me. Some samples had good yield. Some did not. The juvenile gills are super duper tiny and yield from them was pretty low as well. Need to look at minimum input into library prep to see if I need to do repeats.

Moving forward how to tackle juvenile gill extractions? Should I use two gills?

Kara Ryan mentioned tackling the \* look up term for it\* individually for the juvenile gills

#### Q's

#### Next Steps

### Date

#### Next Steps

### Date

#### Next Steps

### Date

### Next Steps

### Notes
